import { PluginFunction, PluginValidateFn, Types } from '@graphql-codegen/plugin-helpers'
import { GraphQLSchema, parse, Kind, InputObjectTypeDefinitionNode, GraphQLInputObjectType, GraphQLNonNull, GraphQLList, GraphQLField, GraphQLInputField } from 'graphql'

export interface ZodPluginConfig {
  /**
   * Import types from this path.
   * @default '@/gql/graphql'
   */
  importFrom?: string
  /**
   * Use Zod v4 record syntax.
   * @default true
   */
  useZodV4?: boolean
  /**
   * Group schemas by module/folder.
   * @default true
   */
  groupByModule?: boolean
  /**
   * Custom scalar mappings.
   * Example: { DateTime: 'z.string()' }
   */
  scalarSchemas?: Record<string, string>
}

const DEFAULT_SCALAR_SCHEMAS: Record<string, string> = {
  ID: 'z.string().min(1)',
  String: 'z.string()',
  Int: 'z.number().int()',
  Boolean: 'z.boolean()',
  Float: 'z.number()',
  DateTime: 'z.string()',
  Email: 'z.string().email()',
  PhoneNumber: 'z.string().min(8)',
  JSON: 'z.record(z.string(), z.any())',
  Upload: 'z.instanceof(File)',
}

export const validate: PluginValidateFn<ZodPluginConfig> = async (
  _schema: GraphQLSchema,
  _documents: Types.DocumentFile[],
  _config: ZodPluginConfig,
  _outputFile: string
) => {
  // Validate config here if needed
}

export const plugin: PluginFunction<ZodPluginConfig> = (
  schema: GraphQLSchema,
  _documents: Types.DocumentFile[],
  config: ZodPluginConfig
) => {
  const scalarSchemas = { ...DEFAULT_SCALAR_SCHEMAS, ...config.scalarSchemas }
  const importFrom = config.importFrom || '@/gql/graphql'

  // Find all Input types from schema
  const typeMap = schema.getTypeMap()
  const inputTypes: Array<{ name: string; node: InputObjectTypeDefinitionNode | null; graphqlType: GraphQLInputObjectType }> = []

  for (const typeName of Object.keys(typeMap)) {
    const type = typeMap[typeName]
    // Skip internal types
    if (typeName.startsWith('__')) continue

    // Check if it's a GraphQLInputObjectType (works for both introspection and SDL schemas)
    // Use constructor.name to avoid instanceof issues with module resolution
    const constructorName = type.constructor?.name
    if (constructorName === 'GraphQLInputObjectType') {
      inputTypes.push({
        name: typeName,
        node: (type.astNode as InputObjectTypeDefinitionNode) || null,
        graphqlType: type as GraphQLInputObjectType,
      })
    }
  }

  // Group inputs by module
  const inputsByModule = new Map<string, string[]>()

  for (const { name, node, graphqlType } of inputTypes) {
    // Only process types ending with Input
    if (!name.endsWith('Input')) continue

    const moduleName = getModuleName(name)
    const schemaCode = generateInputSchema(name, node, graphqlType, scalarSchemas)

    const existing = inputsByModule.get(moduleName) || []
    inputsByModule.set(moduleName, [...existing, schemaCode])
  }

  // Generate output
  let output = `/* eslint-disable */\n`
  output += `/**\n * @graphql-codegen/zod\n * Generated by graphql-codegen\n */\n\n`

  // Add imports
  output += `import { z } from 'zod'\n`

  output += '\n'

  // Generate schemas by module
  if (config.groupByModule !== false) {
    for (const [moduleName, schemas] of inputsByModule) {
      if (schemas.length === 0) continue

      output += `// ============ ${moduleName.toUpperCase()} ============\n\n`
      output += schemas.join('\n\n')
      output += '\n\n'
    }
  } else {
    for (const [, schemas] of inputsByModule) {
      output += schemas.join('\n\n')
      output += '\n\n'
    }
  }

  return {
    content: output,
  }
}

function getModuleName(typeName: string): string {
  // CreateXxxInput -> create-xxx
  // UpdateXxxInput -> update-xxx
  // XxxInput -> xxx
  const name = typeName
    .replace(/Input$/, '')
    .replace(/Create|Update|Delete/gi, '')
    .toLowerCase()

  // Map to actual module names in the project
  const moduleMap: Record<string, string> = {
    'signin': 'auth',
    'signup': 'auth',
    'user': 'users',
    'password': 'auth',
    'reset': 'auth',
    'memorial': 'memorials',
    'post': 'posts',
    'comment': 'comments',
    'invitation': 'invitations',
    'invoice': 'invoices',
    'contact': 'contacts',
  }

  for (const [key, module] of Object.entries(moduleMap)) {
    if (name.includes(key)) {
      return module
    }
  }

  // Return empty string for types that don't map to actual modules
  // These will be grouped under an empty module name and skipped for imports
  return ''
}

function generateInputSchema(
  typeName: string,
  node: InputObjectTypeDefinitionNode | null,
  graphqlType: GraphQLInputObjectType,
  scalarSchemas: Record<string, string>
): string {
  const schemaName = `${typeName.replace(/Input$/, '')}InputSchema`

  const fields: string[] = []

  // Use astNode.fields if available, otherwise use graphqlType.getFields()
  if (node?.fields) {
    for (const field of node.fields) {
      const fieldName = field.name.value
      const fieldType = generateFieldType(field.type, scalarSchemas)
      fields.push(`    ${fieldName}: ${fieldType}`)
    }
  } else {
    // Fallback for introspection-based schemas
    const typeFields = graphqlType.getFields()
    for (const field of Object.values(typeFields)) {
      const fieldName = field.name
      const fieldType = generateFieldTypeFromField(field, scalarSchemas)
      fields.push(`    ${fieldName}: ${fieldType}`)
    }
  }

  return `export function ${schemaName}() {
  return z.object({
${fields.join(',\n')}
  })
}`
}

function generateFieldType(type: any, scalarSchemas: Record<string, string>): string {
  // Handle wrapped types (NonNull, List)
  let baseType: string
  let isOptional = true
  let isArray = false

  // Unwrap the type
  let currentType = type
  while (currentType) {
    if (currentType.kind === Kind.NON_NULL_TYPE) {
      isOptional = false
      currentType = currentType.type
    } else if (currentType.kind === Kind.LIST_TYPE) {
      isArray = true
      currentType = currentType.type
    } else {
      // Named type
      break
    }
  }

  // Handle both AST nodes (with .name.value) and introspection types (with .name as string)
  const typeName = typeof currentType.name === 'object' ? currentType.name.value : currentType.name

  // Check for custom scalars
  if (typeName in scalarSchemas) {
    baseType = scalarSchemas[typeName]
  } else if (typeName.endsWith('Input')) {
    // Nested input type
    baseType = `${typeName.replace(/Input$/, '')}InputSchema()`
  } else if (typeName === 'JSONObject') {
    baseType = 'z.record(z.string(), z.any())'
  } else {
    baseType = 'z.string()' // fallback
  }

  // Apply modifiers
  if (isArray) {
    baseType = `z.array(${baseType})`
  }

  if (isOptional) {
    baseType = `${baseType}.optional()`
  }

  return baseType
}

function generateFieldTypeFromField(
  field: GraphQLInputField,
  scalarSchemas: Record<string, string>
): string {
  // Handle wrapped types (NonNull, List)
  let baseType: string
  let isOptional = true
  let isArray = false

  // Unwrap the type - use constructor name instead of instanceof due to module resolution issues
  let currentType: any = field.type
  while (currentType) {
    const constructorName = currentType.constructor.name
    if (constructorName === 'GraphQLNonNull') {
      isOptional = false
      currentType = currentType.ofType
    } else if (constructorName === 'GraphQLList') {
      isArray = true
      currentType = currentType.ofType
    } else {
      // Named type
      break
    }
  }

  const typeName = currentType?.name

  // Check for custom scalars
  if (typeName && typeName in scalarSchemas) {
    baseType = scalarSchemas[typeName]
  } else if (typeName && typeName.endsWith('Input')) {
    // Nested input type
    baseType = `${typeName.replace(/Input$/, '')}InputSchema()`
  } else if (typeName === 'JSONObject') {
    baseType = 'z.record(z.string(), z.any())'
  } else {
    baseType = 'z.string()' // fallback
  }

  // Apply modifiers
  if (isArray) {
    baseType = `z.array(${baseType})`
  }

  if (isOptional) {
    baseType = `${baseType}.optional()`
  }

  return baseType
}

export default { plugin, validate }
