import { PluginFunction, PluginValidateFn, Types } from '@graphql-codegen/plugin-helpers'
import { GraphQLSchema, parse, Kind, InputObjectTypeDefinitionNode } from 'graphql'

export interface ZodPluginConfig {
  /**
   * Import types from this path.
   * @default '@/gql/graphql'
   */
  importFrom?: string
  /**
   * Use Zod v4 record syntax.
   * @default true
   */
  useZodV4?: boolean
  /**
   * Group schemas by module/folder.
   * @default true
   */
  groupByModule?: boolean
  /**
   * Custom scalar mappings.
   * Example: { DateTime: 'z.string()' }
   */
  scalarSchemas?: Record<string, string>
}

const DEFAULT_SCALAR_SCHEMAS: Record<string, string> = {
  ID: 'z.string().min(1)',
  String: 'z.string()',
  Int: 'z.number().int()',
  Boolean: 'z.boolean()',
  Float: 'z.number()',
  DateTime: 'z.string()',
  Email: 'z.string().email()',
  PhoneNumber: 'z.string().min(8)',
  JSON: 'z.record(z.string(), z.any())',
  Upload: 'z.instanceof(File)',
}

export const validate: PluginValidateFn<ZodPluginConfig> = async (
  _schema: GraphQLSchema,
  _documents: Types.DocumentFile[],
  _config: ZodPluginConfig,
  _outputFile: string
) => {
  // Validate config here if needed
}

export const plugin: PluginFunction<ZodPluginConfig> = (
  schema: GraphQLSchema,
  _documents: Types.DocumentFile[],
  config: ZodPluginConfig
) => {
  const scalarSchemas = { ...DEFAULT_SCALAR_SCHEMAS, ...config.scalarSchemas }
  const importFrom = config.importFrom || '@/gql/graphql'

  // Find all Input types from schema
  const typeMap = schema.getTypeMap()
  const inputTypes: Array<{ name: string; node: InputObjectTypeDefinitionNode }> = []

  for (const typeName of Object.keys(typeMap)) {
    const type = typeMap[typeName]
    // Skip internal types
    if (typeName.startsWith('__')) continue

    // Check if it has an AST node and is an Input type
    if (type.astNode && type.astNode.kind === Kind.INPUT_OBJECT_TYPE_DEFINITION) {
      inputTypes.push({
        name: typeName,
        node: type.astNode as InputObjectTypeDefinitionNode,
      })
    }
  }

  // Group inputs by module
  const inputsByModule = new Map<string, string[]>()

  for (const { name, node } of inputTypes) {
    // Only process types ending with Input
    if (!name.endsWith('Input')) continue

    const moduleName = getModuleName(name)
    const schemaCode = generateInputSchema(name, node, scalarSchemas)

    const existing = inputsByModule.get(moduleName) || []
    inputsByModule.set(moduleName, [...existing, schemaCode])
  }

  // Generate output
  let output = `/* eslint-disable */\n`
  output += `/**\n * @graphql-codegen/zod\n * Generated by graphql-codegen\n */\n\n`

  // Add imports
  output += `import { z } from 'zod'\n`

  // Collect all input type names for import
  const allInputTypeNames = inputTypes
    .filter(t => t.name.endsWith('Input'))
    .map(t => t.name.replace(/Input$/, ''))

  if (allInputTypeNames.length > 0) {
    output += `import type { ${allInputTypeNames.join(', ')} } from '${importFrom}'\n`
  }

  output += '\n'

  // Generate schemas by module
  if (config.groupByModule !== false) {
    for (const [moduleName, schemas] of inputsByModule) {
      if (schemas.length === 0) continue

      output += `// ============ ${moduleName.toUpperCase()} ============\n\n`
      output += schemas.join('\n\n')
      output += '\n\n'
    }
  } else {
    for (const [, schemas] of inputsByModule) {
      output += schemas.join('\n\n')
      output += '\n\n'
    }
  }

  return {
    content: output,
  }
}

function getModuleName(typeName: string): string {
  // CreateXxxInput -> create-xxx
  // UpdateXxxInput -> update-xxx
  // XxxInput -> xxx
  const name = typeName
    .replace(/Input$/, '')
    .replace(/Create|Update|Delete/gi, '')
    .toLowerCase()

  // Map to module names
  const moduleMap: Record<string, string> = {
    'signin': 'auth',
    'signup': 'auth',
    'user': 'auth',
    'password': 'auth',
    'reset': 'auth',
    'memorial': 'memorials',
    'post': 'posts',
    'comment': 'comments',
    'invitation': 'invitations',
    'invoice': 'invoices',
    'contact': 'contacts',
    'banner': 'banners',
    'product': 'products',
    'cart': 'carts',
    'filter': 'filters',
    'pagination': 'pagination',
    'sort': 'sort',
    'query': 'query',
  }

  for (const [key, module] of Object.entries(moduleMap)) {
    if (name.includes(key)) {
      return module
    }
  }

  return 'common'
}

function generateInputSchema(
  typeName: string,
  node: InputObjectTypeDefinitionNode,
  scalarSchemas: Record<string, string>
): string {
  const schemaName = `${typeName.replace(/Input$/, '')}InputSchema`

  const fields: string[] = []

  for (const field of node.fields || []) {
    const fieldName = field.name.value
    const fieldType = generateFieldType(field.type, scalarSchemas)
    fields.push(`    ${fieldName}: ${fieldType}`)
  }

  return `export function ${schemaName}() {
  return z.object({
${fields.join('\n')}
  })
}`
}

function generateFieldType(type: any, scalarSchemas: Record<string, string>): string {
  // Handle wrapped types (NonNull, List)
  let baseType: string
  let isOptional = true
  let isArray = false

  // Unwrap the type
  let currentType = type
  while (currentType) {
    if (currentType.kind === Kind.NON_NULL_TYPE) {
      isOptional = false
      currentType = currentType.type
    } else if (currentType.kind === Kind.LIST_TYPE) {
      isArray = true
      currentType = currentType.type
    } else {
      // Named type
      break
    }
  }

  const typeName = currentType.name.value

  // Check for custom scalars
  if (typeName in scalarSchemas) {
    baseType = scalarSchemas[typeName]
  } else if (typeName.endsWith('Input')) {
    // Nested input type
    baseType = `${typeName.replace(/Input$/, '')}InputSchema()`
  } else if (typeName === 'JSONObject') {
    baseType = 'z.record(z.string(), z.any())'
  } else {
    baseType = 'z.string()' // fallback
  }

  // Apply modifiers
  if (isArray) {
    baseType = `z.array(${baseType})`
  }

  if (isOptional) {
    baseType = `${baseType}.optional()`
  }

  return baseType
}

export default { plugin, validate }
